### ISSUE TITLE
Clojure websocket server + CLJS client

### ISSUE THREAD

**Issue by azureus89** [224-1/xtnt-micro#4] opened 2019-07-16 09:46 UTC

**Comment by VikramShawFL** [comment] 2019-07-22 03:28
Can you please elaborate a bit about this issue.

**Comment by azureus89** [comment] 2019-07-22 07:39
Just like ring boilerplate .. I need a boilerplate websocket server .. and a simple html client interface to recieve and send messages ..

**Comment by VikramShawFL** [comment] 2019-07-24 17:57
I haven't worked on websocket yet, so can you please tell me which library to use because there are many libraries which I'm not able to understand. So please suggest me a library to use with a better documentation. And refer me some links for clojurescript also.

**Comment by azureus89** [comment] 2019-07-24 19:38
Use http-kit
guide/example : https://yogthos.net/posts/2015-06-11-Websockets.html

Because this is slightly old, you may have dependency issues, make sure you use latest versions of the libraries in your project.clj.

For cljs help, ask anyone else on the team, if you have issues running it etc

**Comment by VikramShawFL** [comment] 2019-07-25 10:15
So I followed the steps mentioned in the above link. Getting error ``Exception in thread "main" Syntax error compiling at (multi_client_ws/handler.clj:38:7).`` Created a new repository because it adds many file while running ``lein new luminus multi-client-ws +http-kit +cljs`` This is the link of the repository https://github.com/VikramShawFL/websockets 
Not able to understand what I need to add to update ``multi-client-ws.middleware/wrap-base`` 
![image](https://user-images.githubusercontent.com/46559614/61866609-1c80cd80-aef3-11e9-9a9b-c4a1ad3f1cf5.png)

**Comment by azureus89** [comment] 2019-07-25 10:16
too complex, let me find a simpler websocket implementation

**Comment by azureus89** [comment] 2019-07-25 10:21
Try this https://samrat.me/posts/2013-07-04-clojure-websockets-with-http-kit/
Again old, so you may have to update the versions of the libraries.

**Comment by VikramShawFL** [comment] 2019-07-26 10:35
Getting this error ``Caused by: clojure.lang.ExceptionInfo: /Users/vikramshaw/xtnt-micro/src/cljs/xtnt_micro/core.cljs [line 21, col 92] The map literal starting with :type on line 6 column 12 contains 7 form(s). Map literals must contain an even number of forms.`` Not sure  what is wrong in cljs.core file.
The random numbers are getting generated. Haven't used ``refreshChart()`` function from the above link for clojurescript as it was calling the ``chartkick.js``
Does it suppose to show the output like this without using ``chartkick.js``.

**Comment by azureus89** [comment] 2019-07-26 12:26
Not interested in that. Who is not doing their job?
Is the documentation for this library bad, or for clojurescript, or has baishakhi/kavya/parikshith not done a good job giving you a clojurescript guide to work with?
Who is not doing their job?

**Comment by VikramShawFL** [comment] 2019-07-26 12:53
Documentation is okay, it's just that he has used chartkick.js which contains 546 lines of JavaScript code, so in order to complete it fast I left that part.
Apart from that I was having problem with adding cljs part to my project which I guess no body knew that which I figured out by myself. Parikshith did sent me a link about cljs and Baishakhi didn't remember how we used cljs for normal project as they're using figwel which is configured by you.

**Comment by azureus89** [comment] 2019-07-26 13:05
Issue is not with chartkick. Issue is fundamentally with your use of cljs. CLJS documentation is not great, the team has not done a good job of letting you know how a cljs project works.
Ask them to create/improve the introduction to cljs documentation urgently.

**Comment by azureus89** [comment] 2019-07-30 09:53
@VikramShawFL do you actually need any clojurescript to close this issue right now? I don't think so from the link i sent you. There is no clojurescript there, why are you trying to make life harder for yourself?

**Comment by azureus89** [comment] 2019-07-30 09:55
which branch are you on .. can you push your latest code please

**Comment by VikramShawFL** [comment] 2019-07-30 09:58
The link which you sent me have used Javascript, to get random numbers and show the numbers through chart. I'm able to get the random numbers. But as per the issue it says CLJS client.

**Comment by azureus89** [comment] 2019-07-30 10:06
Then ask me to change the issue if it is causing so many problems. I've made it your responsibility to get your tasks done fast. Being lazy is a value. You have to negotiate with me to make issues as simple as possible so you can close it fast. I might ask you to push the bar up.

I will only give you what you ask me ... if you tell me examples are bad, ill give you better examples, documentation is bad, someone has to improve documentation. But I need you to have respect for your time ... and tell me dude, i cannot do this CLJS thing right now until someone explains it to me first, its clearly not simple. Let me do it in html and close the issue. Make a separate issue to migrate it to CLJS.

I can only fix the hole you identify ... better documentation, better examples/references etc
Its upto you to tell me if you are wasting time trying to make something work, and want to just close this issue and deal with the something else separately.

What is the problem here ... is it the issue itself ... is the issue too broad ... is the reason why you're not able to close this issue because CLJS integration is much more complex and deserves to be a separate issue in itself.

You have to tell me.

**Comment by VikramShawFL** [comment] 2019-07-30 10:40
Ok then can we have a CLJS integration separate issue.

**Comment by azureus89** [comment] 2019-07-30 10:48
Okay ... do the client in HTML and close this issue with a running websocket server.

This has to integrate with current master, so make sure you are synced with master before you submit pull request.

**Comment by VikramShawFL** [comment] 2019-07-30 10:53
Ok what do you want me to show in client side because right now I'm getting only this output
![image](https://user-images.githubusercontent.com/46559614/62123783-4ddc0d80-b2e6-11e9-92d9-9fc5d674d1a8.png)

**Comment by azureus89** [comment] 2019-07-30 18:58
Check console for errors and check the reference article for what you are supposed to get. If all good, submit pull request.

**Comment by VikramShawFL** [comment] 2019-07-31 04:42
I have checked the link thoroughly. He has explained 3 parts 1)Project setup 2)Websocket server 3)Front end and all the 3 parts I already did. The output which I'm getting is the correct one because it is coded to generate the random numbers only. 
Now when I accessing this using ``http://localhost:8080/happiness`` I'm getting the output like the above one(image) and when I'm using an chrome extension(simple websocket client)
![image](https://user-images.githubusercontent.com/46559614/62184432-b0331d80-b37b-11e9-9cd8-074d32624ac5.png)

**Comment by azureus89** [comment] 2019-07-31 10:36
okay merging and closing issue

**Comment by azureus89** [comment] 2019-07-31 10:37
submit pull request please

**Comment by VikramShawFL** [comment] 2019-07-31 10:42
Don't merge it as I've created a new web socket with proper client side messaging boilerplate. It just I'm getting a error which I'm resolving now
![image](https://user-images.githubusercontent.com/46559614/62205855-04ef8c00-b3ae-11e9-88e8-62f70b2f5ad7.png)

**Comment by azureus89** [comment] 2019-07-31 10:45
I wont merge until you send me a pull request and i review conflicts anyway :)

**Comment by VikramShawFL** [comment] 2019-07-31 10:46
Okay.

**Comment by azureus89** [comment] 2019-07-31 10:46
you may want to keep chat for another issue ... a chat boilerplate issue ... create that issue and push this code for that instead. This is just a websocket server and front end simple. Would prefer to merge with only that.

**Closed as completed** 2019-08-01 10:13 UTC
