### ISSUE TITLE
REPL not starting if branched out of master branch

### ISSUE THREAD

**Issue by ParikshithMohan** [224-1/xtnt-micro#20] opened 2019-08-05 06:43 UTC
On doing `lein run 8000` from the shell it shows this: `No :main namespace specified in project.clj`

On doing `cider-jack-in`, the repl establishes a connection in some random port number but on running the specified localhost, the page does not work.

Issue #6 had to be done using html and not clj because of this problem. For now, issue #6 has been completed.

**Comment by VikramShawFL** [comment] 2019-08-05 07:07
@ParikshithMohan  ``No :main namespace`` error is because of two reason 1) You don't have ``-main`` function in core.clj file and 2) You haven't added ``:main xtnt-micro.core`` in project.clj

**Comment by azureus89** [comment] 2019-08-05 08:38
@VikramShawFL .. this is part of what is needed to make the project work .. should be included in the boilerplate .. your responsibility is to make the project boileprlate work .. this is related to #12 .. this is a boilerplate bug .. works only as uberjar .. needs the repls but also lein run to work .. assigning this issue that you ...
As of now what works .. this issue is limited to making lein run work .. use #12 for making the repls work .. 

Not part of parikshiths issue scope to add those functions .. it should be there in the boilerplate, every stable clojure project should work on repls and lein run .. otherwise development is hard .. 

What parikshith is reporting is baaically that your project doesn't work except as an executable. Please fix.

**Comment by kattakavya** [comment] 2019-08-06 09:30
Even I'm facing the same issue with cider-jack-in-cljs, the connection between local server and repl  is not establishing. couldn't able to execute the project.

**Comment by azureus89** [comment] 2019-08-06 09:42
@VikramShawFL push the code that has the repls working and then lein ... priority on repls ... clj and cljs repls need to work ... have to merge into master, please push fixes if done and submit pull request ...

**Comment by azureus89** [comment] 2019-08-06 09:44
3 things need to work:
from emacs: cider-jack-in
from emacs: cider-jack-in-cljs
from shell: lein run

**Comment by azureus89** [comment] 2019-08-06 14:36
@VikramShawFL whats getting in the way?

**Comment by VikramShawFL** [comment] 2019-08-06 15:07
I just messed up. In afternoon both clj and cljs repl was working fine don't know where I messed up now whenever I run cider-jack-in-cljs it opens up clj repl and the other issue is not able to see the chat msg, not getting any errors I'm able to type the msg and but after entering the msg it doesn't show on the screen. So doing all over again.

**Comment by VikramShawFL** [comment] 2019-08-06 15:08
What is the use of lein run when we can just run cider-jack-in-cljs and directly it opens the browser?

**Comment by azureus89** [comment] 2019-08-06 17:01
cider is linked to emacs.
lein is the direct interface with JVM.
Specifically lein run is a portable way of running the server.
The other is via uberjar ... which is useful in production.
During coding, you use the repl.
For dev servr / testing and for testing in different environments you use lein run,
For final deployment on production server you use uberjar, immutant, docker etc.

If deployment and execution issues come later when the project size complexity grows it would be harder to solve. Now is the right time to solve it.

**Comment by azureus89** [comment] 2019-08-06 17:05
difference for dev server between lein and uberjar is that ... uberjar is a compiled jar file, its static. Lein run compiles are runs but recompiles main code. Its not as flexible as the repl though, its inbetween.
with lein run, compojure routes if changed wont recompile, but if you change hiccup in a route it will recompile for instance. So for dev server, testing etc, which we havent got into yet its important.

Its also important from the use case parikshith had ... repl not working.
repl is a very complex thing that has lot of advantages, but sometimes the repl wont work ... im sure everyone has faced that issue. At that time, in order to just show that the code works, lein run is very useful. It allows you to close the issue and report that the repl was giving errors, but the code was working.

**Comment by VikramShawFL** [comment] 2019-08-07 08:25
From emacs cider-jack-in: working
From emacs cider-jack-in-cljs: working

When running lein run I'm getting this error 
``Vikrams-MacBook-Pro:xtnt-micro vikramshaw$ lein run 
Exception in thread "main" Syntax error compiling at (/private/var/folders/2q/yk46mh910jx_zfflrscctm3m0000gn/T/form-init12974320098193869245.clj:1:126).
	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:620)
	at java.base/java.lang.Integer.<init>(Integer.java:1117)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at clojure.lang.Reflector.invokeConstructor(Reflector.java:305)
	at xtnt_micro.handler$_main.invokeStatic(handler.clj:59)
	at xtnt_micro.handler$_main.doInvoke(handler.clj:56)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:380)
	at user$eval140.invokeStatic(form-init12974320098193869245.clj:1)
	at user$eval140.invoke(form-init12974320098193869245.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 12 more``

One more issue I'm facing is with websocket I'm entering the message in the form but it is not showing me in the chat box. On checking the console it says 
![image](https://user-images.githubusercontent.com/46559614/62607331-88aff800-b91b-11e9-8887-51688f0d0821.png)

**Comment by VikramShawFL** [comment] 2019-08-08 06:44
@azureus89 Can you help me with the above error?

**Comment by azureus89** [comment] 2019-08-08 07:04
Please push latest code.

**Comment by VikramShawFL** [comment] 2019-08-08 07:05
I already did that. It's in vk-4-websocket branch

**Comment by azureus89** [comment] 2019-08-08 21:17
Looking into it tomorrow morning ... any progress from your side?

**Comment by VikramShawFL** [comment] 2019-08-09 04:24
No, I tried it read articles also but couldn't find the solution.

**Comment by azureus89** [comment] 2019-08-09 08:40
Haven't tried but based on the documentation, this is what I think is going wrong, all issues are related.

Currently the server side (clj) does not have a main function that rungs the http-kit server ... this is causing two problems:

a) lein run doesn't work
b) websocket doesnt work

Lein run doesn't work because it needs a main function, I dont see a main function in your code. Check http kit documentation http://www.http-kit.org/server.html#options

Websocket doesn't work because right now the server is not started because of above when you run cider-jack-in. It gets started only when you run cider-jack-in-cljs -- it gets started indirectly from the client side, using the :ring-handler hook which is in your project.clj figwheel options.

This hook is only useful for started normal ring servers, you cant use it to start websocket servers.

Create a -main function - dont rely on the ring-handler hook. Once you do that and you run lein run, it will start the full websocket http-kit sever for you.

**Comment by VikramShawFL** [comment] 2019-08-09 09:09
Added the main function in handler.clj & the namespace in project.clj and implemented the figwheel-main but having the same issue again.

**Comment by azureus89** [comment] 2019-08-09 11:27
run only the clj server, kill everything else ... tell me if the server runs ... start with that/ Report any errors.

**Comment by azureus89** [comment] 2019-08-09 11:28
lein run and report errors

**Comment by VikramShawFL** [comment] 2019-08-09 11:56
On running cider-jack-in: clj-cider works but the server doesn't.
On running lein run in both the case i.e before and after cider-jack-in it's giving me the same error
```
Vikrams-MacBook-Pro:xtnt-micro vikramshaw$ lein run
Exception in thread "main" Syntax error compiling at (/private/var/folders/2q/yk46mh910jx_zfflrscctm3m0000gn/T/form-init12743141218686687703.clj:1:126).
	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:620)
	at java.base/java.lang.Integer.<init>(Integer.java:1117)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at clojure.lang.Reflector.invokeConstructor(Reflector.java:305)
	at xtnt_micro.handler$_main.invokeStatic(handler.clj:59)
	at xtnt_micro.handler$_main.doInvoke(handler.clj:56)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:380)
	at user$eval140.invokeStatic(form-init12743141218686687703.clj:1)
	at user$eval140.invoke(form-init12743141218686687703.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 12 more```

**Comment by azureus89** [comment] 2019-08-09 12:46
give me the whole error message ... this is truncated

**Comment by VikramShawFL** [comment] 2019-08-09 12:56
this is the message when I run ``lein run``
```
bash-3.2$ lein run
Exception in thread "main" Syntax error compiling at (/private/var/folders/2q/yk46mh910jx_zfflrscctm3m0000gn/T/form-init3893408366385769387.clj:1:125).
	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:620)
	at java.base/java.lang.Integer.<init>(Integer.java:1117)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at clojure.lang.Reflector.invokeConstructor(Reflector.java:305)
	at xtnt_micro.handler$_main.invokeStatic(handler.clj:59)
	at xtnt_micro.handler$_main.doInvoke(handler.clj:56)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:380)
	at user$eval140.invokeStatic(form-init3893408366385769387.clj:1)
	at user$eval140.invoke(form-init3893408366385769387.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 12 more```

**Comment by azureus89** [comment] 2019-08-09 13:02
Find a way to get me the whole message, this is truncated too ... "12 lines more" ... I need those 12 lines ... but from what I can see I think the issue is that
you have a dev profile ... and whenever there is a dev profile, it takes that as the default profile. You've not defined a main namespace for your dev profile. By default it looks for core.clj, so usually you dont have to define it or worry, but you've changed the main namespace to handler.clj. So you need to set :main for the :dev profile also.

Right now xtnt-micro/handler is set as the main namespace globally, for cljs and for uberjar, but not for your clj :dev profile.

**Comment by azureus89** [comment] 2019-08-09 13:04
Leinegen docs on profiles: https://github.com/technomancy/leiningen/blob/stable/doc/PROFILES.md

this lists out the profile names that are automatically assumed to be the default profile unless lein is run with the with-profile flag specifically running another profile.

**Comment by VikramShawFL** [comment] 2019-08-09 14:11
It's not expanding even though after using few commands and I've added main namespace in project.clj. if I have to add main namespace inside the dev profile then I have to write -dev-main function in the handler.clj right
```	
Vikrams-MacBook-Pro:xtnt-micro vikramshaw$ lein run | more
Exception in thread "main" Syntax error compiling at (/private/var/folders/2q/yk46mh910jx_zfflrscctm3m0000gn/T/form-init10018185215645233088.clj:1:126).
        at clojure.lang.Compiler.load(Compiler.java:7647)
        at clojure.lang.Compiler.loadFile(Compiler.java:7573)
        at clojure.main$load_script.invokeStatic(main.clj:452)
        at clojure.main$init_opt.invokeStatic(main.clj:454)
        at clojure.main$init_opt.invoke(main.clj:454)
        at clojure.main$initialize.invokeStatic(main.clj:485)
        at clojure.main$null_opt.invokeStatic(main.clj:519)
        at clojure.main$null_opt.invoke(main.clj:516)
        at clojure.main$main.invokeStatic(main.clj:598)
        at clojure.main$main.doInvoke(main.clj:561)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:37)
Caused by: java.lang.NumberFormatException: null
        at java.base/java.lang.Integer.parseInt(Integer.java:620)
        at java.base/java.lang.Integer.<init>(Integer.java:1117)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at clojure.lang.Reflector.invokeConstructor(Reflector.java:305)
        at xtnt_micro.handler$_main.invokeStatic(handler.clj:59)
        at xtnt_micro.handler$_main.doInvoke(handler.clj:56)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.Var.invoke(Var.java:380)
        at user$eval140.invokeStatic(form-init10018185215645233088.clj:1)
        at user$eval140.invoke(form-init10018185215645233088.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7176)
        at clojure.lang.Compiler.eval(Compiler.java:7166)
        at clojure.lang.Compiler.load(Compiler.java:7635)
        ... 12 more
(END)
```

**Comment by azureus89** [comment] 2019-08-09 15:23
> if I have to add main namespace inside the dev profile then I have to write -dev-main function in the handler.clj right

huh, why?
what is -dev-main ... only -main is there in your code.

**Comment by VikramShawFL** [comment] 2019-08-10 16:34
Yes only -main function is there in project.clj. I mean to say that we used to write -dev-main function where we used to use wrap-reload like this
![image](https://user-images.githubusercontent.com/46559614/62824254-df862d80-bbb8-11e9-9115-7554fb624254.png)

**Comment by azureus89** [comment] 2019-08-10 21:02
Right.  What I mean is there is no reason to have a
                   -dev-main just because thers a dev profile. You can
                   indicate  anything  as  your  main function for any
                   given  profile,  so here you'd use main only, there
                   are no other functions.

**Comment by VikramShawFL** [comment] 2019-08-13 10:07
I'm stuck here only not able to figure out what's the error

**Comment by azureus89** [comment] 2019-08-13 13:50
@VikramShawFL merged the fix into your vk-4 branch.
Add the optional port assignment code, make it work - find out what the issue was with it exactly.

**Comment by azureus89** [comment] 2019-08-13 14:04
fix optional port assignment and push and submit pull request today, without which i will merge existing to master, because kavya and parikshith are waiting

**Comment by azureus89** [comment] 2019-08-14 14:30
@ParikshithMohan @kattakavya this has been fixed, please start working from your project branches here on cljs

**Closed as completed by azureus89** 2019-08-14 14:30 UTC
